language: php
php:
  - 5.6
  - 7.0
before_script:

script:
    - composer install
    - cd Test/Phpunit
    - composer install
    - vendor/bin/phpunit
    - cd ../Behat/symfony
    - composer install
    - cd ../
    - composer install
    - vendor/bin/behat
    - cd ../codeSniffer
    - composer install
    - vendor/bin/phpcs

matrix:
    allow_failures:
        - php: 7.0

notifications:
    on_failure: always
    on_change: always
